version: '3'

services:
  rangobot:
    build: .
    environment:
      HOST: 0.0.0.0
      PORT: 8070
    command: bash -c "python src/main.py"
    networks:
      - crypto_net

networks:
  crypto_net:
    external: true